version: '2'
services:
  db:
    environment:
      - POSTGRES_PASSWORD=123
    image: postgres
  redis:
    image: redis
  web:
    environment:
      - CASACALIDA_DB_USER=postgres
      - CASACALIDA_DB_PASSWORD=123
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db