# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-16 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('deviceId', models.PositiveIntegerField()),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('xml', models.CharField(blank=True, default='', max_length=255)),
                ('deviceType', models.CharField(blank=True, default='', max_length=255)),
                ('isAwake', models.BooleanField(default=False)),
                ('vendor', models.CharField(blank=True, default='', max_length=255)),
                ('brand', models.CharField(blank=True, default='', max_length=255)),
                ('product', models.CharField(blank=True, default='', max_length=255)),
                ('image', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
