# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-19 19:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=40)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deviceId', models.PositiveIntegerField()),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('xml', models.TextField(blank=True, default='')),
                ('deviceType', models.CharField(blank=True, default='', max_length=255)),
                ('isAwake', models.BooleanField(default=False)),
                ('vendor', models.CharField(blank=True, default='', max_length=255)),
                ('brand', models.CharField(blank=True, default='', max_length=255)),
                ('product', models.CharField(blank=True, default='', max_length=255)),
                ('image', models.TextField(blank=True, default='')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'devices',
                'ordering': ('name',),
            },
        ),
    ]
