# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-07 17:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=40)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Controller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name',),
                'verbose_name_plural': 'controllers',
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deviceId', models.PositiveIntegerField()),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('xml', models.TextField(blank=True, default='')),
                ('deviceType', models.CharField(blank=True, default='', max_length=255)),
                ('isAwake', models.BooleanField(default=False)),
                ('vendor', models.CharField(blank=True, default='', max_length=255)),
                ('brand', models.CharField(blank=True, default='', max_length=255)),
                ('product', models.CharField(blank=True, default='', max_length=255)),
                ('image', models.TextField(blank=True, default='')),
                ('batteryType', models.CharField(blank=True, default='', max_length=255)),
                ('batteryCount', models.PositiveIntegerField(blank=True, default=0)),
                ('controller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Controller')),
            ],
            options={
                'ordering': ('name',),
                'verbose_name_plural': 'devices',
            },
        ),
        migrations.CreateModel(
            name='DeviceBattery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('value', models.PositiveIntegerField()),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Device')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=5)),
                ('description', models.TextField()),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Device')),
            ],
            options={
                'ordering': ('language',),
                'verbose_name_plural': 'descriptions',
            },
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensorId', models.PositiveIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('commandClass', models.CharField(blank=True, default='', max_length=25)),
                ('type', models.CharField(blank=True, default='', max_length=255)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('scale', models.CharField(blank=True, default='', max_length=100)),
                ('valueType', models.CharField(blank=True, default='', max_length=100)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Device')),
            ],
            options={
                'ordering': ('sensorId',),
                'verbose_name_plural': 'sensors',
            },
        ),
        migrations.CreateModel(
            name='SensorValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, default='', max_length=100)),
                ('updated', models.DateTimeField()),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Sensor')),
            ],
            options={
                'ordering': ('-updated',),
                'verbose_name_plural': 'sensorvalues',
            },
        ),
    ]
