# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-22 11:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'ordering': ('name',), 'verbose_name_plural': 'devices'},
        ),
        migrations.AddField(
            model_name='device',
            name='updated',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 5, 22, 11, 13, 12, 247305, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='device',
            name='image',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='device',
            name='xml',
            field=models.TextField(blank=True, default=''),
        ),
    ]
