# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-07 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='deviceId',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='sensorId',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
