# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-20 00:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20160620_0155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='batteryCount',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
