# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-07 19:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20160707_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='icon',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='sensor',
            name='tags',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='sensor',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
