# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 13:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_jobdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actuator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actuatorId', models.CharField(blank=True, default='', max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('commandClass', models.CharField(blank=True, default='', max_length=25)),
                ('type', models.CharField(blank=True, default='', max_length=255)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('icon', models.CharField(blank=True, default='', max_length=255)),
                ('tags', models.CharField(blank=True, default='', max_length=255)),
                ('scale', models.CharField(blank=True, default='', max_length=100)),
                ('valueType', models.CharField(blank=True, default='', max_length=100)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Device')),
            ],
            options={
                'ordering': ('actuatorId',),
                'verbose_name_plural': 'actuators',
            },
        ),
        migrations.CreateModel(
            name='ActuatorValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, default='', max_length=100)),
                ('updated', models.DateTimeField()),
                ('actuator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Actuator')),
            ],
            options={
                'ordering': ('-updated',),
                'verbose_name_plural': 'actuatorvalues',
            },
        ),
        migrations.RemoveField(
            model_name='jobdata',
            name='device',
        ),
        migrations.RemoveField(
            model_name='jobdata',
            name='type',
        ),
    ]
