# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 13:22
from __future__ import unicode_literals

from django.db import migrations

def delete_jobdata(apps, schema_editor):
    JobData = apps.get_model('core', 'JobData')
    for job in JobData.objects.all():
        job.delete()

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_actuator'),
    ]

    operations = [
        migrations.RunPython(delete_jobdata),
    ]
