# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 13:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_deletejobs'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdata',
            name='actuator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Actuator'),
            preserve_default=False,
        ),
    ]
