# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 14:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_final_actuators'),
    ]

    operations = [
        migrations.AddField(
            model_name='controller',
            name='apiUser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.ApiUser'),
        ),
    ]
