# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 14:37
from __future__ import unicode_literals

from django.db import migrations

from django.conf import settings

def migrate_apiuser(apps, schema_editor):
    Controller = apps.get_model('core', 'Controller')
    ApiUser = apps.get_model('core', 'ApiUser')
    for controller in Controller.objects.all():
        apiUser = ApiUser.objects.get(user=controller.owner)
        controller.apiUser = apiUser
        controller.save()

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_controller_apiuser'),
    ]

    operations = [
        migrations.RunPython(migrate_apiuser),
    ]
