# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 14:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_controller_migrate_apiuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='controller',
            name='owner',
        ),
        migrations.AlterField(
            model_name='controller',
            name='apiUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ApiUser'),
        ),
    ]
