# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 10:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_owner_from_controller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobdata',
            name='actuator',
        ),
        migrations.RemoveField(
            model_name='jobdata',
            name='owner',
        ),
        migrations.DeleteModel(
            name='JobData',
        ),
    ]
