# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_jobdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='protocol',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
