# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-06 19:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_device_protocol'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbreviation', models.CharField(max_length=5)),
                ('language', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'languages',
                'ordering': ('abbreviation',),
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Language')),
            ],
            options={
                'verbose_name_plural': 'messages',
            },
        ),
    ]
